FROM openjdk:11-jre-slim


WORKDIR /app


COPY coder-gate/target/coder-gate-0.0.1-SNAPSHOT.jar /app/coder-gate-0.0.1-SNAPSHOT.jar


EXPOSE 8080


CMD ["java", "-jar", "coder-gate-0.0.1-SNAPSHOT.jar"]
