FROM nginx:stable-alpine


COPY coder-gate-ui/dist/ /usr/share/nginx/html


RUN rm /etc/nginx/conf.d/default.conf

WORKDIR group19/

COPY nginx.conf /etc/nginx/conf.d/


EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]
