FROM openjdk:11-jdk-slim

WORKDIR /app 

COPY csci5308vm19/deployment/backend/coder-gate-0.0.1-SNAPSHOT.jar app/coder-gate-0.0.1-SNAPSHOT.jar

EXPOSE 8080

CMD ["java", "-jar", "coder-gate-0.0.1-SNAPSHOT.jar"]
